### ISSUE TITLE
 Possible improvement for the speaker app to onboarding process for 2023

### ISSUE THREAD

**Issue by joedolson** [wpa11yday/wpaccessibilityday#1]
This was an idea I discussed with @joedolson in #organize-speakers on Slack.

1. Gravity Form for speaker applications creates "pending" sessions.
2. Sessions that are selected get changed to draft status. (Manually by speaker team.)
3. Speaker onboarding form includes a dropdown that uses Gravity Perks Populate Anything to allow speakers to select their session from the draft session posts. There is a checkbox on this form to denote if the person is the lead speaker.
4. Lead speaker is able to update the title and description of the draft session post.
5. On submission of the speaker onboarding form speaker posts are automatically connected to the session.
6. After the schedule is finalized all pending sessions (from non-selected talks) are deleted.

Additional improvements needed for next time (applies to both speakers and volunteers):
- If selecting no t-shirt, the mailing address fields should be hidden/not required.
- If getting a t-shirt and outside of the USA, a phone field needs to be required (the shipping company wants this)
- Pass profile info to user account as well as the people post

Copied from https://github.com/wpaccessibility/wpaccessibilityday/issues/21

**Comment by amberhinds** [comment]
I'll take this.

**Comment by amberhinds** [comment]
I have made these updates:

- Gravity Form for speaker applications creates "pending" sessions.
- Speaker onboarding form includes a dropdown that uses Gravity Perks Populate Anything to allow speakers to select their session from the draft session posts. 
- There is a checkbox on the speaker onboarding form to denote if the person is the lead speaker.
- The payment information is only for lead speakers
- Mailing address is only if you want a check payment or a t-shirt
- Added phone for shipping.

I didn't do this: Pass profile info to user account as well as the people post - because I removed the account creation completely. I think that we should just have speakers also register as attendees once we know if we're doing Zoom or not.

There are two things that require code. I'm not sure who wants to take it - @joedolson @lefty55104 @NicktheGeek @alexstine 

1. Linking the person to the draft session.
2. Allowing the lead speaker to update the draft session.

I had hoped I could do this in a no-code way, but it's not fully possible without adding a code snippet. [Here's a tutorial from Gravity Perks that explains what needs to be done to update an existing post from a Gravity Form submission.](https://gravitywiz.com/how-to-update-posts-with-gravity-forms/)

Let me know if we want to abandon this or code the rest.

**Comment by joedolson** [comment]
Should make the same change for mailing address on volunteer forms. 

Regarding linking the person to the draft session: you mean setting the post meta values to relate the speaker post to the session post, right? That's very similar to what I just did for #18, so I'm happy to take that. 

Allowing the lead speaker to update the draft session: that does sound like a bit of a hassle. I feel like that would be easier to do outside of gravity forms, and just build from scratch. If we still created user accounts and assigned the submitter as the post author, we could create an easy relationship to populate a form that only that user could edit.

**Comment by amberhinds** [comment]
I just confirmed that this is complete and functional. Thanks for that code @joedolson!
