### ISSUE TITLE
Fork theme

### ISSUE THREAD

**Issue by joedolson** [wpa11yday/wpaccessibilityday#7]
After resolving #3 and #2. fork this theme to create a separate theme used for the main WP Accessibility Day site.

**Comment by amberhinds** [comment]
I'm wondering if it makes sense to fork this for the main site. The main site is going to be more basic and won't need a lot of what is in this theme. Would it be better to just put a different theme on the main site?

Does @NicktheGeek have a starter? We do, but it's really raw so I'm not sure how helpful it would be unless we want to do a ton of styling.  What about using one of the Twenty X themes?

Just curious if that would get us further faster than forking what we currently have.

**Comment by joedolson** [comment]
My motivation for forking is to use the same underlying code for both sites, to simplify maintenance while minimizing extra work in the immediate future.

**Comment by amberhinds** [comment]
👍 sounds good. I definitely want whatever is easiest.

**Comment by NicktheGeek** [comment]
We *just* started using a new starter at reaktiv. I'm about half way through the very first project that is using it. I think I've found most of the bugs :)

It's a bit of a hybrid template/action oriented theme that uses theme.json to set a lot of the variables and then does a lot with CSS variables through the very bare bones scss.

It's pretty cool, but it would be a project to set it up.

Instead of "forking" it, what do you think about making a parent/child theme. I'm assuming there will be a lot on the event site that is identical to the main site. So if the main site were the parent theme, with templates and styles that are specific to the main site removed, and the event site were a child theme with the bits from the main site removed, it should minimize double the work to maintain things. ie, find a bug that needs fixed that applies to both sites so now you have to edit two themes instead of 1.

**Comment by joedolson** [comment]
A parent/child might work, although then we'd have to check whether changes to the parent changed things on every archive event site, which could get quite burdensome down the road. 

I usually don't like parent/child themes much, but I don't need to have everything my way!

**Comment by NicktheGeek** [comment]
That's a good point, but maybe with a couple of solutions.

1. Generate an HTML site for the past events when it is ready to archive. No theme, no edits, no WordPress updates etc. 
2. Merge the parent/child into a new archive theme for the site when ready to archive. Still have to maintain WordPress, but that's fairly trivial on a network.

**Comment by joedolson** [comment]
We're not using a network at the moment, so that's not currently helpful. 

But shifting archive sites to static is something to consider. I don't think there's anything in those that would prevent that.

**Comment by joedolson** [comment]
Closing this, as the root issue is resolved; but opening a new issue for long-term decisions about what to do with old sites.
